id = "scss"
name = "SCSS & SASS"
description = "SCSS and SASS support"
version = "0.2.0"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-scss"

[grammars.scss]
repository = "https://github.com/simeonoff/tree-sitter-scss"
rev = "3f918284a73a54b53e4f326b0aa8c74ccbf4ee4d"

[grammars.sassdoc]
repository = "https://github.com/simeonoff/tree-sitter-sassdoc"
rev = "38abe86eac15ed8d668de04df963ef0a4c220cfe"

[grammars.sass]
repository = "https://github.com/bajrangCoder/tree-sitter-sass"
rev = "fb280c41b070657e4ff4d4e5e6eea6cb19efd9b8"

[language_servers.scss-lsp]
name = "SCSS Language Server"
languages = ["SCSS"]

[language_servers.some-sass-lsp]
name = "Some Sass Language Server"
languages = ["SCSS", "SASS"]

[language_servers.some-sass-lsp.language_ids]
"SCSS" = "scss"
"SASS" = "sass"
